// Full decompile of dumps/u1-nrf9e5-8051.bin (the nRF9E5's embedded 8051 image,
// extracted from the MC9S08 flash - see docs/nrf9e5-firmware.md). All 19
// functions the tool could reach by following every CALL/ACALL/LCALL
// transitively from the interrupt vectors + known entry points (the
// auto-analyzer finds 0 functions on a raw image with no declared entry
// point). Generated by tools/ghidra/DecompileAll8051.java via
// tools/analyze-8051.sh - see docs/ghidra/README.md.
//
// GHIDRA NAMES SEVERAL SFR ADDRESSES WRONG for this chip (generic 8051/8052
// conventions vs. the nRF9E5's own radio/SPI/GPIO-wakeup/watchdog functions),
// and the P2 GPIO-to-radio bit mapping and nRF905 SPI opcode set aren't in
// Ghidra's naming at all. All of that - and the register table for the code
// below - is in docs/ghidra/register-map.md, sourced from the nRF9E5 Product
// Specification v1.6. Short version used throughout: P2_3 = nRF905 chip
// select, P2_4 = TX_EN(write)/EOC(read), P2_5 = TRX_CE(write)/DR(read);
// opcode 0x00 = W_RF_CONFIG, 0x20 = W_TX_PAYLOAD, 0x22 = W_TX_ADDRESS,
// 0x24 = R_RX_PAYLOAD; F_2fb is the generic SPI byte-transfer primitive.
//
// THE PAYLOAD PIPELINE (who writes vs. who sends - full narrative in
// docs/ghidra/README.md "Who writes the payload, who sends it"): F_3dc is the
// UART RX ISR-driven command dispatcher (fed one byte at a time from F_29f).
// It is the MC9S08 -> 8051 side of the link - the MC9S08 (see
// docs/ghidra/mc9s08gt32_full.c) shifts serial command bytes to the 8051 over
// what is electrically the same SPI/SCI wiring used to boot it
// (docs/nrf9e5-firmware.md). F_3dc recognizes:
//   0x01-0x1F  = a payload of that many bytes follows -> copied byte-by-byte
//                into the 8051's own 32-byte ring buffer (DAT_INTMEM_70..,
//                indices wrap 0x1F->0x00) via DAT_INTMEM_74 (fill count)
//   0x55/0x56  = P2_5 (TRX_CE) clear/set - radio disable/enable
//   0x73       = next byte is a register/config access (state machine 's')
//   0x74/0x75  = clear/set a flag (DAT_INTMEM_26)
//   0x76       = begin a 4-byte little-endian value load into DAT_INTMEM_2b/c
//   0xC0       = report 9 bytes (dumps.670[0..8], part of the F_120 RF_CONFIG
//                literal) back over the UART - a readback/self-test command
// F_3cc sets the two trigger flags once the ring buffer is filled; FORCED_30b
// (below) is what actually drains it into the nRF905 via W_TX_PAYLOAD. So:
// the MC9S08 composes the message (FUN_ce01/db22 in mc9s08gt32_full.c) and
// pushes it byte-by-byte over the wire; the 8051 here is a dumb byte-relay
// that copies whatever arrives straight into the nRF905's TX payload register
// - it never inspects or computes payload content itself.
//
// Ghidra's decompiler could not resolve the constructor at PIC-style
// direct-page indexing in F_3dc's copy loop precisely (marked "Possible PIC
// construction" below) - the ring-buffer index math is a little unusual for
// that reason but the surrounding logic (fill count, wraparound at 0x1F) is
// unambiguous from the raw values.
//
// TX SEND, closing the loop (force-decompiled separately, appended at the end
// of this file as FORCED_30b @ 0x030b and FORCED_4fd @ 0x04fd - they sit
// outside the call graph DecompileAll8051.java walks from the interrupt
// vectors, since F_3cc calls them via a direct address not resolved as a
// named function until forced):
//
//   FORCED_30b (called from F_3cc once the MC9S08 has filled the ring buffer,
//   flags _0_7 && _1_0 both set) is the actual transmit routine:
//     1. CE=0 (P2_5), CSN=0 (P2_3), send W_TX_PAYLOAD (opcode 0x20), then
//        shift out DAT_INTMEM_74 bytes from the ring buffer over SPI: this is
//        the exact moment the MC9S08's message becomes the nRF905's payload.
//     2. CSN=1, clear the two trigger flags.
//     3. Carrier-sense backoff: poll P2_6 (CD, carrier detect) - if the
//        channel is busy, delay and retry up to 5 times (DAT_INTMEM_2d) before
//        giving up and moving on. This is ShockBurst-level collision
//        avoidance, done here in the 8051, not the MC9S08.
//     4. TX_EN=1 (P2_4), CE=1 (P2_5) - actually key the transmitter - then
//        busy-wait on P2_5 (shared pin, now reads DR = "data sent") for the
//        nRF905 to signal TX complete, then CE=0.
//   So FORCED_30b is where "the nRF9E5 actually sends them" happens, and the
//   answer to "what code writes the payload vs. sends it" is: the MC9S08
//   writes it into the 8051's ring buffer over the shared serial link, and
//   FORCED_30b is the only place that byte range is ever handed to the
//   nRF905 hardware (via W_TX_PAYLOAD + SPI shift-out).
//
//   FORCED_4fd is the mirror in the RX direction: enqueues one byte (from
//   BANK0_R2) into a second, separate ring (DAT_INTMEM_72/0x150) and sets TI
//   (UART TX interrupt flag) to push it back out over the serial link to the
//   MC9S08. F_1c8 (the RX-payload reader) and F_3dc's 0xC0 readback command
//   both call it - so this is how received radio bytes (or the 0xC0
//   self-test readback) travel back to the MC9S08 side.
//
########## VECTOR TABLE (8051 interrupt vectors, 0x0000-0x002B) ##########
  0x0000 reset / 0x0003 ext_int0 / 0x000b timer0 / 0x0013 ext_int1 / 0x001b timer1 / 0x0023 serial

########## thunk_FUN_CODE_002b @ CODE:0000  size=3 ##########

/* WARNING: Removing unreachable block (CODE,0x0067) */
/* WARNING: Removing unreachable block (CODE,0x006d) */
/* WARNING: Removing unreachable block (CODE,0x003f) */
/* WARNING: Removing unreachable block (CODE,0x0049) */
/* WARNING: Removing unreachable block (CODE,0x0051) */
/* WARNING: Removing unreachable block (CODE,0x0053) */
/* WARNING: Removing unreachable block (CODE,0x0055) */
/* WARNING: Removing unreachable block (CODE,0x0057) */
/* WARNING: Removing unreachable block (CODE,0x0078) */
/* WARNING: Removing unreachable block (CODE,0x007e) */
/* WARNING: Removing unreachable block (CODE,0x0082) */

void thunk_FUN_CODE_002b(char param_1)

{
  undefined1 *puVar1;
  
  SP = 0x7f;
  F_66c();
  if (param_1 == '\0') {
    puVar1 = (undefined1 *)0xff;
    do {
      *puVar1 = 0;
      puVar1 = puVar1 + -1;
    } while (puVar1 != (undefined1 *)0x0);
    DAT_INTMEM_23 = 0;
    _0_0 = 0;
    _0_1 = 0;
    _0_2 = 0;
    DAT_INTMEM_24 = 0;
    DAT_INTMEM_25 = 0;
    DAT_INTMEM_26 = 0;
    DAT_INTMEM_27 = 0;
    DAT_INTMEM_2a = 0;
    DAT_INTMEM_2d = 0;
    _0_5 = 0;
    _0_6 = 0;
    _0_7 = 0;
    _1_0 = 1;
    DAT_INTMEM_70 = 0;
    DAT_INTMEM_71 = 0;
    DAT_INTMEM_72 = 0;
    DAT_INTMEM_73 = 0;
    DAT_INTMEM_74 = 0;
    DAT_INTMEM_75 = 0;
    DAT_INTMEM_76 = 0;
    DAT_INTMEM_77 = 0;
    DAT_INTMEM_78 = 1;
    DAT_INTMEM_79 = 0;
    DAT_INTMEM_7a = 0;
    DAT_INTMEM_7b = 0;
  }
  F_cb();
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}



########## FUN_CODE_002b @ CODE:002b  size=165 ##########

/* WARNING: Removing unreachable block (CODE,0x0067) */
/* WARNING: Removing unreachable block (CODE,0x006d) */
/* WARNING: Removing unreachable block (CODE,0x003f) */
/* WARNING: Removing unreachable block (CODE,0x0049) */
/* WARNING: Removing unreachable block (CODE,0x0051) */
/* WARNING: Removing unreachable block (CODE,0x0053) */
/* WARNING: Removing unreachable block (CODE,0x0055) */
/* WARNING: Removing unreachable block (CODE,0x0057) */
/* WARNING: Removing unreachable block (CODE,0x0078) */
/* WARNING: Removing unreachable block (CODE,0x007e) */
/* WARNING: Removing unreachable block (CODE,0x0082) */

void FUN_CODE_002b(char param_1)

{
  undefined1 *puVar1;
  
  SP = 0x7f;
  F_66c();
  if (param_1 == '\0') {
    puVar1 = (undefined1 *)0xff;
    do {
      *puVar1 = 0;
      puVar1 = puVar1 + -1;
    } while (puVar1 != (undefined1 *)0x0);
    DAT_INTMEM_23 = 0;
    _0_0 = 0;
    _0_1 = 0;
    _0_2 = 0;
    DAT_INTMEM_24 = 0;
    DAT_INTMEM_25 = 0;
    DAT_INTMEM_26 = 0;
    DAT_INTMEM_27 = 0;
    DAT_INTMEM_2a = 0;
    DAT_INTMEM_2d = 0;
    _0_5 = 0;
    _0_6 = 0;
    _0_7 = 0;
    _1_0 = 1;
    DAT_INTMEM_70 = 0;
    DAT_INTMEM_71 = 0;
    DAT_INTMEM_72 = 0;
    DAT_INTMEM_73 = 0;
    DAT_INTMEM_74 = 0;
    DAT_INTMEM_75 = 0;
    DAT_INTMEM_76 = 0;
    DAT_INTMEM_77 = 0;
    DAT_INTMEM_78 = 1;
    DAT_INTMEM_79 = 0;
    DAT_INTMEM_7a = 0;
    DAT_INTMEM_7b = 0;
  }
  F_cb();
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}



########## F_cb @ CODE:00cb  size=85 ##########

void F_cb(undefined2 param_1)

{
  undefined1 uVar1;
  undefined1 uVar2;
  
  uVar2 = (undefined1)param_1;
  uVar1 = (undefined1)((ushort)param_1 >> 8);
  DAT_SFR_ab = 0xff;
  DAT_SFR_ac = 0xff;
  DAT_SFR_ad = 8;
  F_120();
  EA = 1;
  P0_0 = 1;
  do {
    if (_0_2 != '\0') {
      _0_2 = '\0';
      DAT_SFR_ab = 0xff;
      DAT_SFR_ac = 0xff;
      DAT_SFR_ad = 8;
    }
    if (_0_6 != '\0') {
      EA = 0;
      uVar1 = DAT_INTMEM_2c;
      uVar2 = DAT_INTMEM_2b;
      F_5a2();
      _0_6 = '\0';
      EA = 1;
    }
    F_566();
    DAT_INTMEM_28 = uVar2;
    DAT_INTMEM_29 = uVar1;
    if (DAT_INTMEM_26 == '\0') {
      if (DAT_INTMEM_27 != '\0') {
        F_3c6();
      }
      F_1c8();
      F_3cc();
    }
    else if (DAT_INTMEM_27 == '\0') {
      F_3be();
    }
  } while( true );
}



########## F_256 @ CODE:0256  size=73 ##########

undefined1 F_256(undefined1 param_1)

{
  undefined1 uVar1;
  undefined1 uVar2;
  undefined1 uVar3;
  undefined1 uVar4;
  undefined1 uVar5;
  undefined1 uVar6;
  undefined1 uVar7;
  undefined1 uVar8;
  undefined1 uVar9;
  
  uVar9 = DAT_INTMEM_22;
  uVar8 = BANK0_R7;
  uVar7 = BANK0_R6;
  uVar6 = BANK0_R5;
  uVar5 = BANK0_R4;
  uVar4 = BANK0_R3;
  uVar3 = BANK0_R2;
  uVar2 = BANK0_R1;
  uVar1 = BANK0_R0;
  TF0 = 0;
  TL0 = 0xe0;
  TH0 = 0xb1;
  _0_2 = 1;
  F_23b();
  BANK0_R1 = uVar2;
  BANK0_R0 = uVar1;
  BANK0_R7 = uVar8;
  BANK0_R6 = uVar7;
  BANK0_R5 = uVar6;
  BANK0_R4 = uVar5;
  BANK0_R3 = uVar4;
  BANK0_R2 = uVar3;
  DAT_INTMEM_22 = uVar9;
  return param_1;
}



########## F_29f @ CODE:029f  size=92 ##########

undefined1 F_29f(undefined1 param_1,undefined1 param_2)

{
  char cVar1;
  undefined1 uVar2;
  undefined1 uVar3;
  undefined1 uVar4;
  undefined1 uVar5;
  undefined1 uVar6;
  undefined1 uVar7;
  undefined1 uVar8;
  undefined1 uVar9;
  undefined1 uVar10;
  
  uVar10 = DAT_INTMEM_22;
  uVar9 = BANK0_R7;
  uVar8 = BANK0_R6;
  uVar7 = BANK0_R5;
  uVar6 = BANK0_R4;
  uVar5 = BANK0_R3;
  uVar4 = BANK0_R2;
  uVar3 = BANK0_R1;
  uVar2 = BANK0_R0;
  cVar1 = RI;
  if (cVar1 != '\0') {
    param_2 = SBUF;
    F_3dc(param_2);
    RI = 0;
  }
  cVar1 = TI;
  if (cVar1 != '\0') {
    TI = 0;
    if (DAT_INTMEM_75 == '\0') {
      _0_0 = 0;
    }
    else {
      F_549();
      SBUF = param_2;
      _0_0 = 1;
    }
  }
  BANK0_R1 = uVar3;
  BANK0_R0 = uVar2;
  BANK0_R7 = uVar9;
  BANK0_R6 = uVar8;
  BANK0_R5 = uVar7;
  BANK0_R4 = uVar6;
  BANK0_R3 = uVar5;
  BANK0_R2 = uVar4;
  DAT_INTMEM_22 = uVar10;
  return param_1;
}



########## F_156 @ CODE:0156  size=114 ##########

void F_156(void)

{
  SCON = 0x50;
  DAT_SFR_b4 = 0;
  IPH1 = 2;
  P2_3 = 0;
  F_2fb(0);
  F_2fb(0x75);
  F_2fb(6);
  F_2fb(0x44);
  F_2fb(0x20);
  F_2fb(0x20);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xd4);
  P2_3 = 1;
  P2_3 = 0;
  F_2fb(0x22);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xea);
  P2_3 = 1;
  return;
}



########## F_1c8 @ CODE:01c8  size=115 ##########

void F_1c8(void)

{
  byte bVar1;
  undefined1 uVar2;
  char cVar3;
  char cVar4;
  byte bVar5;
  
  bVar1 = BANK0_R2;
  cVar3 = '\0';
  P2_4 = 0;
  P2_5 = 1;
  cVar4 = P2_5;
  if (cVar4 != '\x01') {
    return;
  }
  if (_0_5 == '\0') {
    P2_5 = 0;
    P2_3 = 0;
    F_2fb(0x24);
    uVar2 = BANK0_R3;
    _0_3 = '\x01';
    _0_4 = '\0';
    BANK0_R2 = bVar1;
    for (cVar4 = ' '; bVar1 = BANK0_R2, cVar4 != '\0'; cVar4 = cVar4 + -1) {
      bVar5 = 0;
      BANK0_R3 = uVar2;
      F_2fb();
      BANK0_R2 = bVar1;
      if ((_0_4 != '\x01') && (_0_1 != '\x01')) {
        if (_0_3 == '\0') {
          if (cVar3 != '\0') {
            cVar3 = cVar3 + -1;
            BANK0_R3 = uVar2;
            func_0x04fd(bVar5);
            BANK0_R2 = bVar1;
          }
        }
        else {
          _0_3 = '\0';
          if ((bVar5 == 0) || (BANK0_R2 = bVar5, 0x20 < bVar5)) {
            _0_4 = '\x01';
            BANK0_R2 = bVar1;
          }
        }
      }
    }
    P2_3 = 1;
    cVar4 = P2_5;
    if (cVar4 != '\0') {
      P2_4 = 1;
      P2_4 = 0;
      do {
        cVar4 = P2_5;
      } while (cVar4 == '\x01');
    }
    BANK0_R3 = uVar2;
    return;
  }
  P2_5 = 0;
  return;
}



########## F_2fb @ CODE:02fb  size=16 ##########

void F_2fb(undefined1 param_1)

{
  byte bVar1;
  undefined1 uVar2;
  
  bVar1 = DAT_SFR_91;
  DAT_SFR_91 = bVar1 & 0xdf;
  IPL1 = param_1;
  do {
    bVar1 = DAT_SFR_91;
  } while ((bVar1 >> 5 & 1) == 0);
  uVar2 = IPL1;
  return;
}



########## F_66c @ CODE:066c  size=4 ##########

void F_66c(void)

{
  return;
}



########## F_120 @ CODE:0120  size=54 ##########

void F_120(void)

{
  P0 = 8;
  DAT_SFR_95 = 6;
  DPX = 0xff;
  DAT_SFR_94 = 2;
  P1 = 8;
  HADDR = 0;
  DAT_SFR_96 = 0;
  IE = 0x12;
  IP = 0;
  TMOD = 1;
  TCON = 0x10;
  TL0 = 0xd0;
  TH0 = 0x8a;
  DAT_SFR_8e = 8;
  RCAP2L = 0xd9;
  RCAP2H = 0xff;
  T2CON = 0x34;
  DAT_SFR_bf = 0x14;
  SCON = 0x50;
  DAT_SFR_b4 = 0;
  IPH1 = 2;
  P2_3 = 0;
  F_2fb(0);
  F_2fb(0x75);
  F_2fb(6);
  F_2fb(0x44);
  F_2fb(0x20);
  F_2fb(0x20);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xd4);
  P2_3 = 1;
  P2_3 = 0;
  F_2fb(0x22);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xea);
  F_2fb(0xea);
  P2_3 = 1;
  return;
}



########## F_5a2 @ CODE:05a2  size=15 ##########

void F_5a2(undefined2 param_1)

{
  DAT_INTMEM_78 = (char)param_1;
  DAT_INTMEM_79 = (char)((ushort)param_1 >> 8);
  DAT_INTMEM_7a = 0;
  DAT_INTMEM_7b = 0;
  return;
}



########## F_566 @ CODE:0566  size=60 ##########

byte F_566(void)

{
  byte bVar1;
  char cVar2;
  undefined2 uVar3;
  
  DAT_INTMEM_7c = DAT_INTMEM_78;
  DAT_INTMEM_7d = DAT_INTMEM_79;
  DAT_INTMEM_7e = DAT_INTMEM_7a;
  DAT_INTMEM_7f = DAT_INTMEM_7b;
  uVar3 = 0x4e6d;
  cVar2 = -0x3a;
  DAT_INTMEM_7b = F_5b1(0x41);
  DAT_INTMEM_78 = (byte)uVar3 + 0x39;
  bVar1 = (char)((ushort)uVar3 >> 8) - (((0xc6 < (byte)uVar3) << 7) >> 7);
  DAT_INTMEM_79 = bVar1 + 0x30;
  DAT_INTMEM_7a = cVar2 - (((0xcf < bVar1) << 7) >> 7);
  return DAT_INTMEM_7b & 0x7f;
}



########## F_3c6 @ CODE:03c6  size=6 ##########

void F_3c6(void)

{
  P2_5 = 0;
  DAT_INTMEM_27 = 0;
  return;
}



########## F_3cc @ CODE:03cc  size=16 ##########

void F_3cc(char param_1)

{
  if (_0_5 != '\0') {
    _0_5 = 0;
    func_0x030b();
    if (param_1 != '\0') {
      _0_1 = 0;
      P0_0 = 1;
    }
    return;
  }
  return;
}



########## F_3be @ CODE:03be  size=8 ##########

void F_3be(void)

{
  DAT_INTMEM_27 = 1;
  P2_4 = 1;
  P2_5 = 1;
  return;
}



########## F_23b @ CODE:023b  size=27 ##########

void F_23b(void)

{
  if (DAT_INTMEM_23 < 0x14) {
    DAT_INTMEM_23 = DAT_INTMEM_23 + 1;
    return;
  }
  DAT_INTMEM_23 = 0;
  if (_0_1 != '\0') {
    DAT_INTMEM_71 = DAT_INTMEM_70;
    DAT_INTMEM_74 = 0;
    _0_1 = '\0';
    DAT_INTMEM_24 = 0;
  }
  return;
}



########## F_3dc @ CODE:03dc  size=289 ##########

/* WARNING: Possible PIC construction at 0x04c8: Changing call to branch */
/* WARNING: Removing unreachable block (CODE,0x04cb) */
/* WARNING: Removing unreachable block (CODE,0x04d1) */

void F_3dc(byte param_1,byte param_2)

{
  bool bVar1;
  byte bVar2;
  byte bVar3;
  byte bVar4;
  char cVar5;
  
  cVar5 = DAT_INTMEM_2a;
  bVar4 = BANK0_R3;
  if (DAT_INTMEM_25 != '\0') {
    if (DAT_INTMEM_25 == 's') {
      param_1 = param_1 * '\x04';
      bVar4 = BANK0_R2 & 0xc;
      P2_3 = 0;
      BANK0_R2 = bVar4;
      F_2fb(0x11);
      bVar3 = 0;
      F_2fb();
      P2_3 = 1;
      BANK0_R2 = bVar4;
      if ((bVar3 & 0xc) != bVar4) {
        BANK0_R3 = BANK0_R3 & 0xf3 | param_1;
        bVar2 = BANK0_R3;
        P2_3 = 0;
        F_2fb(1,bVar3 & 0xc);
        BANK0_R3 = bVar2;
        F_2fb(bVar3);
        P2_3 = 1;
      }
      DAT_INTMEM_25 = 0;
      return;
    }
    if (DAT_INTMEM_25 != 'v') {
      DAT_INTMEM_25 = 0;
      return;
    }
    DAT_INTMEM_2a = DAT_INTMEM_2a + -8;
    BANK0_R3 = param_1;
    bVar4 = 0;
    cVar5 = cVar5 + -7;
    while (cVar5 = cVar5 + -1, cVar5 != '\0') {
      bVar1 = CARRY1(param_2,param_2);
      param_2 = param_2 * '\x02';
      bVar4 = bVar4 << 1 | bVar1;
    }
    DAT_INTMEM_2b = DAT_INTMEM_2b | param_2;
    DAT_INTMEM_2c = DAT_INTMEM_2c | bVar4;
    if (DAT_INTMEM_2a == '\0') {
      DAT_INTMEM_25 = 0;
      _0_6 = 1;
      return;
    }
    return;
  }
  if (DAT_INTMEM_24 == 0) {
    if ((param_1 == 0) || (0x1f < param_1)) {
      if (param_1 == 0xc0) {
        for (bVar3 = 0; (bVar3 < 9) << 7 < '\0'; bVar3 = bVar3 + 1) {
          BANK0_R3 = bVar4;
          func_0x04fd(CONCAT11(6,*(undefined1 *)((ushort)bVar3 + 0x670)));
        }
        BANK0_R3 = bVar4;
        return;
      }
      if (param_1 == 0x55) {
        P2_5 = 0;
        return;
      }
      if (param_1 == 0x56) {
        P2_5 = 1;
        return;
      }
      if (param_1 != 0x73) {
        if (param_1 == 0x74) {
          DAT_INTMEM_26 = 1;
          return;
        }
        if (param_1 != 0x75) {
          if (param_1 != 0x76) {
            return;
          }
          DAT_INTMEM_2a = 0x10;
          DAT_INTMEM_2b = 0;
          DAT_INTMEM_2c = 0;
          DAT_INTMEM_25 = 0x76;
          return;
        }
        DAT_INTMEM_26 = 0;
        return;
      }
      DAT_INTMEM_25 = 0x73;
      return;
    }
    _0_1 = 1;
    DAT_INTMEM_23 = 0;
    DAT_INTMEM_24 = param_1;
  }
  if (DAT_INTMEM_74 != ' ') {
    *(byte *)(DAT_INTMEM_70 + '0') = BANK0_R2;
    if (DAT_INTMEM_70 == '\0') {
      DAT_INTMEM_70 = '\x1f';
    }
    else {
      DAT_INTMEM_70 = DAT_INTMEM_70 + -1;
    }
    DAT_INTMEM_74 = DAT_INTMEM_74 + '\x01';
    return;
  }
  return;
}



########## F_549 @ CODE:0549  size=29 ##########

void F_549(void)

{
  if (DAT_INTMEM_75 != '\0') {
    BANK0_R2 = *(undefined1 *)(DAT_INTMEM_73 + 'P');
    if (DAT_INTMEM_73 == '\0') {
      DAT_INTMEM_73 = '\x1f';
    }
    else {
      DAT_INTMEM_73 = DAT_INTMEM_73 + -1;
    }
    DAT_INTMEM_75 = DAT_INTMEM_75 + -1;
  }
  return;
}



########## F_5b1 @ CODE:05b1  size=110 ##########

char F_5b1(char param_1,ushort param_2,byte param_3)

{
  short sVar1;
  byte bVar2;
  byte bVar3;
  byte bVar4;
  byte bVar5;
  byte bVar6;
  byte bVar7;
  byte bVar8;
  
  bVar8 = (byte)(param_2 >> 8);
  bVar2 = (byte)((param_2 & 0xff) * (ushort)DAT_INTMEM_7c >> 8);
  bVar4 = (byte)((ushort)bVar8 * (ushort)DAT_INTMEM_7c);
  sVar1 = (param_2 & 0xff) * (ushort)DAT_INTMEM_7d;
  bVar3 = (byte)((ushort)sVar1 >> 8);
  bVar2 = ((char)((ushort)bVar8 * (ushort)DAT_INTMEM_7c >> 8) - ((CARRY1(bVar4,bVar2) << 7) >> 7)) -
          ((CARRY1((byte)sVar1,bVar4 + bVar2) << 7) >> 7);
  bVar4 = bVar3 + bVar2;
  bVar5 = (byte)((ushort)param_3 * (ushort)DAT_INTMEM_7c);
  bVar6 = bVar5 + bVar4;
  bVar7 = (byte)((ushort)bVar8 * (ushort)DAT_INTMEM_7d);
  sVar1 = (param_2 & 0xff) * (ushort)DAT_INTMEM_7e;
  return (char)param_2 * DAT_INTMEM_7f +
         bVar8 * DAT_INTMEM_7e +
         param_3 * DAT_INTMEM_7d +
         param_1 * DAT_INTMEM_7c +
         (char)((ushort)sVar1 >> 8) +
         (((char)((ushort)bVar8 * (ushort)DAT_INTMEM_7d >> 8) +
          (((char)((ushort)param_3 * (ushort)DAT_INTMEM_7c >> 8) +
           (-((CARRY1(bVar5,bVar4) << 7) >> 7) - ((CARRY1(bVar3,bVar2) << 7) >> 7))) -
          ((CARRY1(bVar7,bVar6) << 7) >> 7))) - ((CARRY1((byte)sVar1,bVar7 + bVar6) << 7) >> 7));
}



// function_count=19

########## FORCED_30b @ CODE:030b  (force-decompiled, outside the walked call graph - see header) ##########

char FORCED_30b(void)

{
  bool bVar1;
  char cVar2;
  char cVar3;
  char cVar4;
  byte bVar5;

  if ((_0_7 != '\0') && (_1_0 != '\0')) {
    P2_5 = 0;
    P2_3 = 0;
    func_0x02fb(0x20);
    while (DAT_INTMEM_74 != '\0') {
      func_0x052c();
      func_0x02fb();
    }
    P2_3 = 1;
    _0_7 = '\0';
    _1_0 = '\0';
  }
  DAT_INTMEM_7c = 0xe0;
  DAT_INTMEM_7d = 0x2e;
  cVar4 = DAT_INTMEM_29;
  bVar5 = DAT_INTMEM_28;
  func_0x061f();
  cVar2 = DAT_INTMEM_2d;
  DAT_INTMEM_2e = 0;
  for (DAT_INTMEM_2f = 0; DAT_INTMEM_2f < (byte)(cVar4 - (((DAT_INTMEM_2e < bVar5) << 7) >> 7));
      DAT_INTMEM_2f = DAT_INTMEM_2f - ((bVar1 << 7) >> 7)) {
    bVar1 = 0xfe < DAT_INTMEM_2e;
    DAT_INTMEM_2e = DAT_INTMEM_2e + 1;
  }
  P2_5 = 1;
  P2_4 = 0;
  DAT_INTMEM_2e = 0;
  for (DAT_INTMEM_2f = 0; cVar4 = ((DAT_INTMEM_2e < 0x78) << 7) >> 7, cVar3 = DAT_INTMEM_2f + cVar4,
      DAT_INTMEM_2f < (byte)-cVar4; DAT_INTMEM_2f = DAT_INTMEM_2f - ((bVar1 << 7) >> 7)) {
    bVar1 = 0xfe < DAT_INTMEM_2e;
    DAT_INTMEM_2e = DAT_INTMEM_2e + 1;
  }
  cVar4 = P2_6;
  if (cVar4 != '\0') {
    _0_5 = 1;
    DAT_INTMEM_2e = 0;
    for (DAT_INTMEM_2f = 0; DAT_INTMEM_2f < 4U - (((DAT_INTMEM_2e < 0xb0) << 7) >> 7);
        DAT_INTMEM_2f = DAT_INTMEM_2f - ((bVar1 << 7) >> 7)) {
      bVar1 = 0xfe < DAT_INTMEM_2e;
      DAT_INTMEM_2e = DAT_INTMEM_2e + 1;
    }
    DAT_INTMEM_2d = DAT_INTMEM_2d + 1;
    cVar3 = cVar2 + -4;
    if (DAT_INTMEM_2d < 5) {
      return cVar3;
    }
  }
  DAT_INTMEM_2d = 0;
  _0_5 = 0;
  P2_4 = 1;
  P2_5 = 1;
  do {
    cVar2 = P2_5;
  } while (cVar2 == '\0');
  P2_5 = 0;
  _1_0 = 1;
  return cVar3;
}



########## FORCED_4fd @ CODE:04fd  (force-decompiled, outside the walked call graph - see header) ##########

void FORCED_4fd(void)

{
  char cVar1;

  if (DAT_INTMEM_75 == ' ') {
    return;
  }
  *(undefined1 *)(DAT_INTMEM_72 + 'P') = BANK0_R2;
  cVar1 = DAT_INTMEM_75;
  if (DAT_INTMEM_72 == '\0') {
    DAT_INTMEM_72 = '\x1f';
  }
  else {
    DAT_INTMEM_72 = DAT_INTMEM_72 + -1;
  }
  DAT_INTMEM_75 = DAT_INTMEM_75 + '\x01';
  if ((cVar1 == '\0') && (_0_0 != '\x01')) {
    TI = 1;
  }
  return;
}
